# File/Path Settings
paths:
  folder_name: 'test3'
  load_folder_name: 'joint_action_5_9_GT_MAAC'
  # model_path, load_path etc. will be constructed from the above in the code

# Environment Settings
env:
  seed: 42
  physics_dt: 0.01
  device: "cuda"

  num_agent: 4
  max_velocity: 1.0
  max_yaw_rate: 35.0 # degrees
  fov: 120.0 # degrees
  cell_size: 0.01 # meter
  sensor_range: 0.3 # meter
  plot: False

  map_representation:
    free: 0
    unknown: 1
    occupied: 2
    goal: 3

  reward_info:
    goal_threshold: 0.2
    goal: 100
    collision: -100


# Agent Settings
agent:
  rollouts: 12
  learning_epochs: 8
  mini_batches: 2

  discount_factor: 0.99
  lambda: 0.95

  learning_rate: 1e-3
  learning_rate_scheduler: null
  learning_rate_scheduler_kwargs: {}

  grad_norm_clip: 1.0
  ratio_clip: 0.1
  value_clip: 0.1
  
  entropy_loss_scale: 0.0
  value_loss_scale: 1.0

  buffer:
    replay_size: 10000
    minimum_size: 2000
    batch_size: 256
    num_episode_buffer: 40
  experiment:
    directory: "MARL"
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: auto

model:
  actor:
    hidden: [256, 256]
  
  critic:
    hidden: [256, 256]
    
# Training Settings
train:
  timesteps: 4800